-- 물고기 종류 별로 가장 큰 물고기의 ID, 물고기 이름, 길이 출력
-- 물고기의 ID 컬럼명은 ID, 이름 컬럼명은 FISH_NAME, 길이 컬럼명은 LENGTH
-- 결과 : 물고기의 ID에 대해서 오름차순 정렬
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO, FISH_NAME_INFO
WHERE FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE AND FISH_INFO.LENGTH = (
        SELECT MAX(LENGTH)
        FROM FISH_INFO
        WHERE FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
)

-- 물고기 종류별로 구분
# SELECT FISH_NAME, LENGTH
# FROM FISH_INFO, FISH_NAME_INFO
# WHERE FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE

-- 물고기 종류별로 가장 큰 물고기 구하기
# SELECT FISH_NAME, MAX(LENGTH)
# FROM FISH_INFO, FISH_NAME_INFO
# WHERE FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
# GROUP BY FISH_NAME
